services:
  php:
    container_name: real_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    container_name: real_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/
    networks:
      - app-network
    depends_on:
      - php

  db:
    image: mysql:latest
    container_name: real-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker/mysql/manage_student.sql:/docker-entrypoint-initdb.d/manage_student.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
